[package]
name = "xash3d-ffi"
description = "Raw FFI bindings to Xash3D FWGS engine"
keywords = ["ffi", "bindings"]
version = "0.1.0"
license = "MIT"
rust-version = "1.64"
edition = "2021"
authors = ["Denis Drakhnia <numas13@gmail.com>"]

[dependencies]
libc = { version = "0.2", default-features = false }
