#include "wrapper-types.h"

#include "common/const.h"
#include "common/cvardef.h"
#include "common/con_nprint.h"
#include "common/usercmd.h"
#include "common/cl_entity.h"
#include "common/com_model.h"
#include "common/kbutton.h"
#include "common/screenfade.h"
#include "common/pmtrace.h"

#include "pm_shared/pm_movevars.h"
#include "common/ref_params.h"

#include "common/wrect.h"
#include "common/particledef.h"
#include "common/beamdef.h"
#include "common/dlight.h"
#include "common/netadr.h"
